### ISSUE TITLE
Trojan win32/tisar.b

### ISSUE THREAD

**Issue by jetpack3331** [gregstein/AoE2Tools#10]
AV detected this release as trojan: win32/tisar.b

**Comment by gregstein** [comment]
Hello,

Thank you for reporting! What's the AV name? Is it Windows Defender? I would appreciate any screenshot that displays the full detection message as well as the file concerned. That way It'll be easier for me to fix.

Thank you,

**Comment by jetpack3331** [comment]
@gregstein Yeah it's windows defender.
Don't have more informations. Only the trojan name. 
File is : https://github.com/gregstein/AoE2Tools/releases/download/3.1.0.7/AoE2Tools.3.1.0.7.exe

**Comment by gregstein** [comment]
Thank you very much! the name you provided is good enough.  I'm currently working on a huge update AoE2Tools 3.2, including WK Cloud Installer (faster wk installer alternative) and a Game Tweaker (run the game at high fps and customization). So Eventually, I will upload a new version and make sure to submit this version to windows defender (before release) to get rid of the false positive flag. So technically it is not worth going through the trouble to submit another report for 3.1.0.7.

For now, you could safely disable Windows defender then install and setup AoE2Tools. Once you are done setting up everything you can turn on your Windows defender antivirus again. Or you can wait for  3.2 to be released. 

Please keep in mind that all popular antivirus security suites have whitelisted AoE2Tools as safe, except windows defender.

**Comment by gregstein** [comment]
Nevermind, I think I will make some time tonight to fix this issue. I will keep you posted.

**Comment by jetpack3331** [comment]
Thx @gregstein :)

**Comment by gregstein** [comment]
Thank you for your patience! I have just received a pm from Microsoft:
![ms_aoe2tools](https://user-images.githubusercontent.com/16618729/49690559-70d96780-fb33-11e8-8994-ea6c0169e565.png)

I copied the steps for you:
·         Go to  https://www.microsoft.com/en-us/wdsi/definitions  

·         Download the corresponding definitions (32 bit or 64 bit based on your operating system)  

·         Run the downloaded file to install the new definitions  

Let me know how that goes!

Thank you,

**Comment by jetpack3331** [comment]
Okay now is everything fine @gregstein :)

**Comment by gregstein** [comment]
Glad to hear that and thanks for reporting 👍
