### ISSUE TITLE
Repository code does not build

### ISSUE THREAD

**Issue by basvd** [gregstein/AoE2Tools#11]
I'm trying to build this project (in VS 2017) after having cloned the repository, but there are many errors.

Certain packages (KryptonToolkitSuite, SharpZipLib) are missing from packages.config. Fixing the package references reveals that some of the packages are incompatible with the solution target framework (which is set to 4.5).

The folders Properties and Resources are missing from HD-to-TC project (WindowsFormsApplication3).

So far I haven't run into other issues, but I have yet to build the code, so we'll see. I am currently fixing what I can and will submit a pull request if I get this to work.

There are no other contributors on this repository, so I suppose this is not a big issue right now, just giving you a heads up.

**Comment by basvd** [comment]
I'm also missing a few external tools and/or their source code (AoE2Tools Mover.exe, AoE2ToolsDiag.exe, Updater.exe). Do you intend to release these as well?

**Comment by gregstein** [comment]
Hello basvd,

Yes! I attend to push the entire source code as soon as I am done with new features (WK Cloud Installer, Game Tweaker) These tools are joining AoE2Tools asap. 

In few days, Im releasing AoE2Tools 3.2 and updating the source code as well. 

**I will make sure to test the source code myself on VS 2017 before i reupload though I prefer and work on VS 2013.**

Thanks,

**Comment by basvd** [comment]
Thanks, I'm looking forward to it! The tools are really good, but the code is messy. Maybe I can help with that.

Right now I'm using your code to rewrite a converter/installer script without GUI. It should work more like an API/library, which will make it easier to improve the GUI without breaking the code. I will let you know when I have something that you can use.

Off-topic questions: I noticed the converter extracts files from base.bina and libc.bin. These files are (original?) game files, correct? Or are they patched/modified in any way? Could distributing them be considered illegal? Are there other ways to generate/download these files?

**Comment by gregstein** [comment]
yeah, thanks! Sorry I like to slap the code in one file I didn't get the hang with classifying things but surely that would help.

Those are just a few original/patched files constituting 5% of the game installation; so definitely legal because the assets are the ones you shouldn't be distributing and are btw generated from a legal copy of hd on steam. Even wololokingdoms works similarly and I wouldn't want to go through extra trouble to generate those particular files.

**Comment by gregstein** [comment]
Repository code has been updated to the latest release 3.2. Please Feel free to open an new issue in case the code is not working.

Thank you!
