### ISSUE TITLE
Modals Lockup AoE2Tools after update to 3.2.0.0

### ISSUE THREAD

**Issue by jcphlux** [gregstein/AoE2Tools#12]
![image](https://user-images.githubusercontent.com/996689/50367364-6496d680-0545-11e9-9f7d-eb25012e2748.png)

**Comment by jcphlux** [comment]
If I right click on app and close it the Modal does not close. I have to go into task manager and end task on it to get it to remove the modal.

**Comment by jcphlux** [comment]
I have uninstalled and reinstalled and the Modals appear to work until the update runs.
![image](https://user-images.githubusercontent.com/996689/50367532-8a70ab00-0546-11e9-976e-c11d3526c3b6.png)
If I don't run this update it still works.

**Comment by gregstein** [comment]
Hello jcphlux,

I have pushed a new update. Run AoE2Tools.exe and you will be asked to download 3.2.0.1. Then you can Try the Launcher as I am pretty sure it'll work now.

Thanks for reporting and let me know how it went.

**Comment by gregstein** [comment]
Feel free to reopen this issue or submit a new one in case this was not helpful.
