### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by Aenor12** [gregstein/AoE2Tools#13]
Hello there, i egt this when i try to update aoe2 tools to 3.5.1
![capture2](https://user-images.githubusercontent.com/46631040/51076535-5a7a7a80-16a2-11e9-8eb9-747080b80560.JPG)

**Comment by gregstein** [comment]
Hello,

Quickly Uninstall AoE2Tools from control panel and then install the latest one: https://github.com/gregstein/AoE2Tools/releases/tag/3.2.0.0

Don't worry! Uninstalling and reinstalling AoE2Tools will not change your game settings in anyway.

**Comment by Aenor12** [comment]
Hello there, thx for answering so fast.
I did that but now i get the following message when trying to re-install aoe2tools.
Thank you in advance
![capture3](https://user-images.githubusercontent.com/46631040/51076884-3ff6d000-16a7-11e9-8d43-c29ae9a0c96d.JPG)

**Comment by gregstein** [comment]
What's with that green border around the error window! It must be a sandbox of your antivirus. You should disable the sandbox on your antivirus.
Then try to reinstall.

**Comment by gregstein** [comment]
I will close this issue because I believe that this issue would be resolved as soon as your disable your antivirus sandbox or run the install off the sandbox.

Feel free to open a new issue if you have further questions.
Thank you for your time!
