### ISSUE TITLE
It does not open after installation

### ISSUE THREAD

**Issue by Divy1211** [gregstein/AoE2Tools#15]
When I try to open it this happens:
![capture](https://user-images.githubusercontent.com/20875997/51885316-f7325d00-23b0-11e9-9d2f-cf33cefa9b84.PNG)
This is what it says in problem details:
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	Launcher.exe
  Problem Signature 02:	3.1.0.4
  Problem Signature 03:	5c1dddde
  Problem Signature 04:	System.Drawing
  Problem Signature 05:	4.7.2116.0
  Problem Signature 06:	59c47740
  Problem Signature 07:	5b3
  Problem Signature 08:	6b
  Problem Signature 09:	System.ArgumentException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

If you are wondering my system specs are as follows:
Windows 7
32 bit
4 GB RAM
Intel(R) Core(TM) i3-2120 CPU @ 3.30 GHz 3.30 GHz
I've tried reinstalling, running with admin perms but still doesn't work

**Comment by gregstein** [comment]
Hello!

Please go to the installation folder of AoE2Tools: Press Windows Button > Run > %appdata%\AoE2Tools

and double click 'AoE2Tools.exe'. Do you see any error?

btw make sure you have  .Net [Framework 4.5](https://www.microsoft.com/en-us/download/details.aspx?id=30653) installed.

Also what Windows 7 edition? Home, Pro, Ultimate?

**Comment by Divy1211** [comment]
Hey! 
I tried to run AoE2Tools.exe but i got the same error, 
I tried installing .Net Framework 4.5 but when i ran the installer, it said that it cannot install because a same or higher version of it was already installed on my computer,
and i have Windows 7 Ultimate

**Comment by gregstein** [comment]
the error log is not helpful enough 'System.ArgumentException' is vague as an error. Please uninstall and make sure to delete folder '%appdata%\AoE2Tools' and then install the latest 3.2.0.6 which comes with 'AoE2Tools.exe' in 32bit [https://github.com/gregstein/AoE2Tools/releases/tag/3.2.0.0](https://github.com/gregstein/AoE2Tools/releases/tag/3.2.0.0) 

Also if you have an antivirus make sure Sandbox option is turned off before initiating the installer.

If after reinstalling AoE2Tools yet the same error. I invite you to scan your computer for rootkits or malware [https://www.malwarebytes.com/](https://www.malwarebytes.com/ ) & [https://www.mcafee.com/enterprise/en-us/downloads/free-tools/stinger.html](https://www.mcafee.com/enterprise/en-us/downloads/free-tools/stinger.html)

Or upgrading to windows 10 is probably a wiser/safer idea as well since the support to Windows 7 is soon to be dropped.

**Comment by Divy1211** [comment]
I tried re-installing after deleting the folder as you said but I still got the same error.

I do not have any Anti-Virus installed so it is not a problem.

Since I do not have an Anti-Virus I do not know for sure if there are any viruses on my computer but there should be none since all things run on my computer without any problems and I've never had this kind of an issue before with anything else.

Upgrading to Windows 10 is not an option for me sadly the computer is old and it may not be able to run Windows 10 properly. (The games work fine and that's all I ask for XD)

Is there any other dependency that I might be lacking which may be causing this problem?

**Comment by gregstein** [comment]
Brother! With these specs "4 GB RAM, Intel(R) Core(TM) i3-2120 CPU @ 3.30 GHz 3.30 GHz" you can run Windows 10 X64bit with better performance than just x32. Windows 10 64bit Requires 1 GB RAM and 60 GB Disk space. Windows 10 upgrade tool will tell you as well if you can upgrade or not but i'm sure 100% you can.

Here, go for it: https://www.microsoft.com/en-us/software-download/windows10

If you see any problems. There is a Downgrade button which should restore your computer back to windows 7, but I highly doubt you would do it. 

When you are doing the upgrade make sure to pick x64 for better performance and more software/games compatibility. 32bit is a limited architecture.

**Comment by Divy1211** [comment]
Hey, I tried running the AoE2Tools on a windows 8.1, 64 bit and it works fine, maybe there is something specific to my computer which is causing this error? I just wanna check out all possibilities before going for that upgrade.
tbh I am a bit hesitant to go for the Windows 10 upgrade because I once upgraded the 8.1 to 10 and I had several problems and it got so bad that I had to downgrade. It had better specs than the Windows 7. Although if it does come down to it, I will try once.

**Comment by gregstein** [comment]
Mind Joining Discord https://discordapp.com/invite/jdCgCyx So we could do some screen sharing or TeamViewer. There are many things to try..

**Comment by Divy1211** [comment]
I joined, i have posted my issue on the discord #issues server

**Comment by gregstein** [comment]
It turned that Divy1211 system is failing to run some .NET applications besides other malfunctionalities and performance issues.
Though we have tried to reinstall .NET and scan the system integrity to no avail. An upgrade to Windows 10 would most definitely fix the problem. Or a clean install of Windows 7.
