### ISSUE TITLE
How can we (the community) Support you? $$

### ISSUE THREAD

**Issue by ZeseAgapen** [gregstein/AoE2Tools#16]
I would like to send you some $ for your work on this project.

**Comment by gregstein** [comment]
Hello Raughnbo,

You could donate through this link [https://streamlabs.com/gregstein_](https://streamlabs.com/gregstein_). Or Right AoE2Tools shield to access the same support link 
![aoe2tools_support](https://user-images.githubusercontent.com/16618729/52432041-c1584b80-2b09-11e9-8bb5-f22af6f1cd93.png)

I highly appreciate your kindness and support that you are showing to this project. Please do not hesitate to request a feature that you would like to see in the future.

Have a great rest of your day.
Warm regards,

**Comment by gregstein** [comment]
OMGGG! Very generous of you Mr. Raughnbo! Thank you so much for the huge support <3

**Comment by gregstein** [comment]
I have messaged you through Discord as well. Feel free to pm me if you need anything really.

Have a great rest of your day and thank you again <3
