### ISSUE TITLE
Watching Reply's

### ISSUE THREAD

**Issue by zikmir** [gregstein/AoE2Tools#17]
Before you could drag and drop files and it would start the reply, now you cannot. Not sure why i cannot watch reply. Any news i am missing?

**Comment by gregstein** [comment]
Hello zikmir!

Don't run AoE2Tools as administrator! Only then you should be able to drag and drop recorded games.

Also if you successfully manage to drag and drop the recorded games but playing them is displaying an error or nothing happens? Just close AoE2Tools and Run AoE2Tools As Administrator then go to Options > Advanced > Fix Association  "http://prntscr.com/mrp28m" . Now close AoE2Tools and run it without admin privileges.

**Comment by gregstein** [comment]
Closed Issue as resolved! Feel free to reopen this issue if you need further help.
