### ISSUE TITLE
could not initialize graphics system

### ISSUE THREAD

**Issue by steveumu1c** [gregstein/AoE2Tools#18]
When I launch offline I get a tiny screen but it imports my hotkeys. I cannot change the screen resolution to more than a tiny window. When I get on Voobly, it tells me on launch that "Could not initialize graphics system. Make sure that your video card and driver are compatible with DirectDraw."

I have windows 10 and an advanced graphics card. Is there something I can do to fix this error?

**Comment by steveumu1c** [comment]
https://answers.microsoft.com/en-us/windows/forum/windows_other-gaming/age-of-empires-ii-could-not-initialize-graphics/06569ca3-7e06-4fd9-a378-714c7f756176?msgId=2e5c952f-6976-4d27-a150-aed061ab21d6&page=2

**Comment by gregstein** [comment]
Hello Steve!

We have an integrated hotfix already included in AoE2Tools. I highly recommend that you use the hotfix so you would never come across that nasty issue. 

I have written a detailed guide on my blog to fix this issue: [Could not initialize graphics system Age of Empires 2 [Fix]](https://ageofnotes.com/resolve-issues/how-to-fix-could-not-initialize-graphics-system-for-age-of-empires-2/)

(First Update AoE2Tools then proceed with these steps)

Step 1 http://prntscr.com/ml85kn

Step 2 http://prntscr.com/ml81qn

Step 3 http://prntscr.com/ml82dx

The hotfix is automated! Essentially you don't need the solutions in the link you have shared above. Besides the hotfix you need [Directplay enabled](https://filestore.community.support.microsoft.com/api/images/b6cf51dc-720b-452d-b82a-0a24f7807751?upload=true). If that feature is not available or you can't see it? Just [download & install DirectX](https://www.microsoft.com/en-us/download/details.aspx?id=35) Then run the game and that should prompt you to install directplay.

**Comment by gregstein** [comment]
Issue closed as resolved. Feel free to reopen.

**Comment by harocopos** [comment]
hi guys , do we have the "out of sync " problem fixed for aoe2 multiplayer on voobly ?

**Comment by gregstein** [comment]
> hi guys , do we have the "out of sync " problem fixed for aoe2 multiplayer on voobly ?

Hello,

That's usually a wk mod issue. So if you have a different wk version you'll get that out of syn.

**Comment by harocopos** [comment]
> > hi guys , do we have the "out of sync " problem fixed for aoe2 multiplayer on voobly ?
> 
> Hello,
> 
> That's usually a wk mod issue. So if you have a different wk version you'll get that out of syn.

I use 1.5rc on voobly not WK .
