### ISSUE TITLE
Missing components in Source Code

### ISSUE THREAD

**Issue by JoseJohnen** [gregstein/AoE2Tools#19]
Hello,

The Source code i downloaded from this site shows me than there are several files missing from the same one, the first one is a Form called "Form" and the respective Form.Designer.cs and Form.resx.

The second is All the images in the Resource Folder.

That will do, thanks in advance

**Comment by gregstein** [comment]
Hello Jose,

I will take a look at it when I'm back to my hometown. Now that I'm browsing the source I see that some files didn't upload at all. I guess GitHub for some reason omitted them when I was uploading but no worries I will fix this.

**Comment by gregstein** [comment]
Thank you for your patience!

The source code has been updated to latest 3.3.0.3 and includes resource files.
Latest commit https://github.com/gregstein/AoE2Tools/commit/df22b1633c7b577ea6f022753d7261fada473641

I will close this issue as resolved but feel free to reopen if someone is wrong.

Have a good day,
