### ISSUE TITLE
Launcher seems to not find AoE2 HD

### ISSUE THREAD

**Issue by CDGJosh** [gregstein/AoE2Tools#2]
When i run the launcher (wether as admin or not) and click on "SCAN FIRST" it gives me the only option to restart, so i click it and get to the main screen where this message then greets me.

![image](https://user-images.githubusercontent.com/3664745/42411969-2a7ce188-8205-11e8-8ca6-140e0b50a4fb.png)

![image](https://user-images.githubusercontent.com/3664745/42411971-305e1c5c-8205-11e8-895e-1a98d8d6639e.png)

![image](https://user-images.githubusercontent.com/3664745/42411845-ae7a5f08-8203-11e8-9b05-735072871625.png)

Age2 HD is correctly fresh installed from steam (verfied again and launched, runs like a charm). Never had voobly nor aoc installed.

Your Application does not seem to generate logfiles (at least i don't find any) otherwise i'd attach them. 

I'am using win 10 with latest updates, no virus scanner and disabled windows defender.

**Comment by CDGJosh** [comment]
Workaround is to manually launch "HDToAoC.exe"

**Comment by gregstein** [comment]
Thank you very much for reporting this! I am glad you launched HDToAoC directly. I am pretty sure you have some registry keys left over of previous aoc installation or you have previously used compatibility patch (I hope I am right about this). Either way I will improve launcher to detect better and show convert button whenever possible. 

I will soon push the next release with this fix.  Thank you again!!

**Comment by gregstein** [comment]
I have pushed a hotfix that should resolve the issue: https://github.com/gregstein/AoE2Tools/releases/download/3.1.0.2/AoE2Tools.Hotfix.exe

**Comment by CDGJosh** [comment]
FYI i've never had a previous aoc installation since this system is still pretty fresh. Only had the steam installation of Age not the disk version or an old converted one.

**Comment by CDGJosh** [comment]
Just testet on my laptop which suffered of the same launcher issue, the hotfix works! Thanks for your work!

**Comment by gregstein** [comment]
Np! And Thank you for taking time to posting images and reporting .
