### ISSUE TITLE
Campaign requires CD

### ISSUE THREAD

**Issue by Cordifhyura** [gregstein/AoE2Tools#21]
Transferred from steam by Tools,Already have UP and wololo installed.Mutiplayer is all right,but whiile startup from single menu with or without Voobly it keeps asking for a CD insert.How could I fix this.

**Comment by gregstein** [comment]
Hello,

Thank you for reminding me about that. Meantime here is a good workaround solution:
1- Download "**Campaigns.zip**" https://www.mediafire.com/file/ji1m44lhr1g33q7/Campaign.zip
2- Run AoE2Tools > Manager > Select Restore Tab > Browse and select "**Campaigns.zip**" > Press "Restore My Back up"
![aoe2tools_manager_campaigns](https://user-images.githubusercontent.com/16618729/56453869-c7a84680-6348-11e9-894f-a856c2fb389d.jpg)

Now you can play the campaigns.

Let me know if you need anything else.

Warm regards,
GregStein

**Comment by gregstein** [comment]
Issue closed as resolved
