### ISSUE TITLE
Persistent Issue

### ISSUE THREAD

**Issue by azaelvaldo** [gregstein/AoE2Tools#22]
I got this permanent error even uninstalling all data and trying run again the tool:

Aplicación: AoE2Tools.exe
Versión de Framework: v4.0.30319
Descripción: el proceso terminó debido a una excepción no controlada.
Información de la excepción: System.Net.WebException
   en System.Net.HttpWebRequest.GetResponse()
   en WindowsFormsApplication3.TestUI+<VooblyHTML>d__40.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   en System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   en System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   en System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   en System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   en System.Threading.ThreadPoolWorkQueue.Dispatch()
   en System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Got this log from event log from windows.

**Comment by gregstein** [comment]
Hello,

Thank you for reporting the issue. Please supply me with your windows version (7,8 or 10?) and your antivirus brand.

**Comment by gregstein** [comment]
If I have to guess.. You probably need to install [.NET Framework 4.5](https://www.microsoft.com/fr-fr/download/details.aspx?id=30653)

Please feel free to reopen the this issue if it's still not resolved
