### ISSUE TITLE
Verify integrity files of aoe2 hd 

### ISSUE THREAD

**Issue by B13Chris** [gregstein/AoE2Tools#25]
ive done this multiple times and hit retry and it brings up the same thing over and over again

**Comment by gregstein** [comment]
Hello B13Chris,

Could you post a screenshot of the error and where it happened so I can help you better?
Now I have to randomly guest a solution:

**Use "Custom?" to select the correct path of your steam installation as demonstrated in the imagery below:**
![custom-path-aoe2tools](https://user-images.githubusercontent.com/16618729/67989068-068d5200-fc32-11e9-9e63-9f530eff945d.png)


**Quick question, do you see "Lang: EN" or something else?**

![detecting english](https://user-images.githubusercontent.com/16618729/67989318-bd89cd80-fc32-11e9-98b8-13054320ad9d.png)

**Comment by gregstein** [comment]
Issue has answered and closed today due to inactivity. Feel free to reopen for further assistance.

have a nice day,
