### ISSUE TITLE
Restore original trees?

### ISSUE THREAD

**Issue by IcySon55** [gregstein/AoE2Tools#26]
Hey guys,

I just ran the latest version of AoE2Tools and converted my HD game and DLCs to TC. Afterwards I also installed WK using the new cloud installer.

At the end of all the setups, I ended up with WK.exe and AOE2Tools.exe as the only two that actually launch the game and have WK civs working. The only problem is that the installation automatically installed small trees... looking at offline voobly mods, small trees is not installed. I tried copying the graphics archive off of my original AoC discs but that didn't fix it.

Why did I get small trees automatically? Small walls is not installed and the walls are normal as expected. Help?

**Comment by IcySon55** [comment]
Ok, so I reset AoE2Tools and did all the installation steps except for WK Cloud. And the trees are still normal size! Great! But I don't have WK now... I tried using the older WK installer but it is unable to start the installation.

... Ok I manually installed WK using the 5.8.1 converter and have now achieved victory with WK working and trees all normal! Woo~

**Comment by gregstein** [comment]
Well! You did not have to reinstall or reset anything. AoE2Tools has an offline mod installer utility which can be used to install or uninstall offline mods. Check out how to do that in 3 steps: #23 


**By default, WK installer comes with small trees, because It helps you see villagers behind large patches of trees or forests And Everyone is using small trees for this reason (if you play multiplayer, you are putting yourself in a huge disadvantage) I can tell.. You have never played multiplayer before or still getting started, but eventually you will install that mod.**

**Comment by IcySon55** [comment]
Actually, I'm not playing through Voobly at all so the offline mods menu didn't help because they're all for Voobly offline. I even uninstalled Voobly as that's not my goal. It's just to get a mostly original copy of the game running well with all the new DLC to play with my wife locally.

**Comment by gregstein** [comment]
Alright! I see now. Probably if you take a look at the gif image below showing why small trees are a must..

![213189j](https://user-images.githubusercontent.com/16618729/68088158-8e56a480-fe5c-11e9-82f2-20f0c03c60ae.gif)

Again! I'm not trying to force you into using it but the gameplay would be much responsive. Feel free to show this gif to your wife as she might have another perspective.

Let me know if you need anything else.
Happy Gaming,

**Comment by IcySon55** [comment]
We're used to them being the way they are.
I watch a bunch of T90 so I know all about them being small too for the pro players.
I also think that the WK Cloud installer should provide options instead of forcing small trees on everyone.

**Comment by gregstein** [comment]
Alright! In the next update I will make sure to provide mod customization for the WK Cloud installer.
Thank you!

**Comment by IcySon55** [comment]
Awesome! Thanks!
