### ISSUE TITLE
Does aoe2tools install Voobly?

### ISSUE THREAD

**Issue by rafaeleyng** [gregstein/AoE2Tools#27]
Is unclear for me whether aoe2tools can install Voobly for me.

[This video](https://youtu.be/LTgb8NII0UM?t=84) appears to say that it installs Voobly (unless I misunderstood it).

Well, I had Voobly previously installed and had an enormous amount of problems (literally 4 hours trying to make things work with aoe2tools without success).

Then I did:
- removed everything: Steam, Age2 HD, Voobly, aoe2tools
- installed Steam and Age2 HD again
- installed aoe2tools, expecting that it would install Vooby for me (selecting "Auto" on "Install Voobly")
- no signal of Voobly, anywhere

I would like to know: does aoe2tools install Voobly for me? Or am I misunderstanding this? If yes, any idea why it is not installing for me?

**Comment by gregstein** [comment]
> does aoe2tools install Voobly for me? Or am I misunderstanding this? If yes, any idea why it is not installing for me?

Yes, AoE2Tools installs Voobly for you but some antivirus protections tend to block the installation. You can either disable your antivirus before proceeding with the conversion with aoe2tools, or download and install voobly client before or after the conversion whatever you like.

**Comment by rafaeleyng** [comment]
Thanks for the answer.
