### ISSUE TITLE
Problems with custom path

### ISSUE THREAD

**Issue by rafaeleyng** [gregstein/AoE2Tools#28]
In the conversion tool, I'm having a really hard time trying to work with custom paths.

First confusion: "Game directory". What is this? The directory where the game is currently installed (I mean, the directory where my Age2 HD is installed, inside Steam? Or is it the directory where I want aoe2tools to output the AoC? I strongly suggest making this more explicit on the UI.

It seems that, in some scenarios (can't figure out when exactly), aoe2tools forces me to have a folder called "age of empires ii" on "Game directory". For instance, if I select "Custom" and try to select "D:\", it goes:

![image](https://user-images.githubusercontent.com/4842605/68261324-82b2db80-001e-11ea-85e7-19f044695312.png)

If I try to create it inside some custom folder, like "D:\aoe2tools", it adds "age of empires ii" and doesn't let me remove it (note: I selected "D:\aoe2tools" and aoe2tools added "age of empires ii"; when I selected "D:\", it didn't add):

![image](https://user-images.githubusercontent.com/4842605/68261521-2603f080-001f-11ea-96bf-ab0da2dcb2cc.png)

Doing and redoing and trying to fix this several times, I ended up with having this:

![image](https://user-images.githubusercontent.com/4842605/68261645-88f58780-001f-11ea-84b1-9a5ac158db13.png)

which is obviously wrong because is duplicating all the folders and files, but aoe2tools wouldn't let me select anything different than that.

I'm really confused and, despite spending a good 6 hours on this today, wasn't able to make this work, specially because of path issues and what I reported #27.

**Comment by rafaeleyng** [comment]
![image](https://user-images.githubusercontent.com/4842605/68264659-47b5a580-0028-11ea-9d23-b6ac8820b692.png)

Trying to use the "AoE2Tools Cloud", got this, which seems to imply that the "age of empires ii" folder is expected.

Edit: to be more clear, this time I've set the "Game directory" as "D:\aoe2ToolsGame", and for some reason the tool added `age of empires ii` later when looking for some file.

**Comment by gregstein** [comment]
Thank you for reporting!

> First confusion: "Game directory". What is this? The directory where the game is currently installed (I mean, the directory where my Age2 HD is installed, inside Steam? Or is it the directory where I want aoe2tools to output the AoC?

**Answer:** It is the directory where you want aoe2tools to output the AoC (Steam assets is the one with the hd installation path)

> It seems that, in some scenarios (can't figure out when exactly), aoe2tools forces me to have a folder called "age of empires ii" on "Game directory".

When AoE2Tools creates a subfolder, it means you have at least one file residing inside "**D:\aoe2tools**". You need to make sure that folder "**D:\aoe2tools**" is empty. 
Also the reason why "D:\" didn't get the subdirectory "age of empires ii", because it's either empty or has only folders in it but no files.

This is a security measure to avoid overwriting files by mistake.

In a few minutes, I'm pushing an update to allow you to manually edit the custom Game directory path so you can basically just use the back arrow in your keyboard to erase "age of empires ii"

I have also addressed the issue with icon in "AoE2Tools Cloud". I'll keep you updated as soon as i push the update.

**Comment by gregstein** [comment]
An update has been to AoE2Tools. You can run **Updater.exe** to install the update. Then proceed with the conversion because now you should be able to remove the "age of empires ii" manually.
Let me know if you need anything else.

**Comment by rafaeleyng** [comment]
Thanks for the answers, I ended up giving up and doing everything manually. If I get to try it again, I'll check this issue and report back.

**Comment by gregstein** [comment]
Sorry for the trouble. Unfortunately, most of the users use the default settings hence less debugging for custom settings. 

A beautiful solution would be to install everything without changing the custom folder, then move the folder anywhere you wish. Then Run AoE2Tools as administrator to change your aoc game path to your custom one:
![change-game-path](https://user-images.githubusercontent.com/16618729/68329426-79cf1200-00d1-11ea-8966-eded522abad5.png)

**Comment by rafaeleyng** [comment]
Yeah, I use a separate partition for the data, so I needed custom paths. Maybe next time I will try your suggestion.

**Comment by gregstein** [comment]
Hello Rafael,

Wonderful! And thank you for reporting the issue as you have contributed in fixing this bug in update 3.3.0.7 which means you can now set your custom directory at the conversion however you like. This last solution is just a workaround for older version of AoE2Tools.

Have a great rest of your day,
