### ISSUE TITLE
Activation key page is giving a 404

### ISSUE THREAD

**Issue by vedant1811** [gregstein/AoE2Tools#30]
this page is https://ageofnotes.com/openkey/ giving a 404.

(Cross posted on reddit: https://www.reddit.com/r/aoe2/comments/hh1acx/i_am_a_404_for_key_verification_using_aoe2tools/ )

**Comment by gregstein** [comment]
Hello Vedant,

Thank you for pointing that out as I have fixed it now. the page is back to working now but if you can't generate your key I recommend to run the page on Internet explorer (Microsoft Edge) or in Incognito window on chrome and then generate your key.

**Comment by vedant1811** [comment]
@gregstein Thank you! Its fixed now.
