### ISSUE TITLE
Any time I try to use HD2AoC, I get "Registry Key is null!"

### ISSUE THREAD

**Issue by Bestulo** [gregstein/AoE2Tools#32]
![image](https://user-images.githubusercontent.com/23301025/90202799-b9d3cb80-ddac-11ea-9dee-ceab928497e0.png)

Which registry key is this and how can I unnull it to run the program?

**Comment by gregstein** [comment]
Hello Bestulo!

Sorry for the delayed answer.

Your AoE2 HD installation is missing a registry key or keys at this location: `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Microsoft Games\Age of Empires II HD`

Solution 1: Use this reg file to restore default values: 
[aoe2hd-reg-fix.zip](https://github.com/gregstein/AoE2Tools/files/5074926/aoe2hd-reg-fix.zip)

Solution 2: Verify the integrity of Age of Empires 2 HD in your Steam Library.

Let me know how it goes.

Warm regards,
GregStein

**Comment by Bestulo** [comment]
Hi. When I joined Voobly lobby and told it to verify my game, it checked that it was not compatible with multiplayer, so in the end I didn't use AoE2Tools but instead had Voobly fix it, and now I can play AoC without going through AoE2Tools. I'd still have liked to solve it, but I don't want to screw things up when they're already working, so I'll leave it at that.

Thank you. I'll save this for future occasions when I change or format my computer and want to re-download.
