### ISSUE TITLE
Activation page is giving a 404 again

### ISSUE THREAD

**Issue by michucz** [gregstein/AoE2Tools#33]
Hi,
thanks for your great work.
As the title says, i am not able to get an ativation key.

**Comment by gregstein** [comment]
Hello Mich,

Thank you for reporting! It's fixed now. And thank you for the donation <3

**Comment by michucz** [comment]
Thank you so much!

also np, wasn't much.

Thank you again for this amazing work.

**Comment by gregstein** [comment]
I appreciate the love friend <3 
Have a great rest of your day.
