### ISSUE TITLE
I cannot get the version 1.0 without c so I cant play a lot of the times with other people

### ISSUE THREAD

**Issue by DanVader137** [gregstein/AoE2Tools#34]
I looked in the version switcher and there is no "1.0" its just "1.0c" which doesn't allow me to play with others that use 1.0 version and that version is the most common version.

**Comment by DanVader137** [comment]
Is there anyway of me getting a 1.0 version?

**Comment by gregstein** [comment]
Hello Dan,
MB for mistakenly not including it but it's there. Just browse to the game folder inside \Age2_x1\ folder you will find all versions concatenated at the of Age2_x1 exe such as: age2_x1.0.exe double click it to run

**Comment by DanVader137** [comment]
Ah ok thank you so much for the help

**Comment by DanVader137** [comment]
Would it be a huge problem if I were to ask you to add this version in the version switcher as when It launches my game on gameranger is automatically launches whatever version is selected on aoe2 tools so I am still not really able to play with people who have 1.0 version.

**Comment by gregstein** [comment]
@DanVader137 Sure brother! Will do soon but for now you make a new copy of "age2_x1.0.exe"  then remove age2_x1.exe and rename "age2_x1.0 Copy.exe" to "age2_x1.exe" so gameranger automatically runs it.

**Comment by DanVader137** [comment]
Alright thank you!!!

**Comment by DanVader137** [comment]
Would you please add it to the version switcher as I can't make it work and I have tried multiple times through the few days I closed this issue.

**Comment by gregstein** [comment]
It's added! Run AoE2Tools and accept the new update then you should see the 1.0 from the selections.

**Comment by DanVader137** [comment]
![image](https://user-images.githubusercontent.com/82294691/115396967-77854880-a1dd-11eb-9cd1-addbb0dbb533.png)

I keep getting this message even after I have reinstalled everything multiple times

**Comment by gregstein** [comment]
[age2_x1.0.zip](https://github.com/gregstein/AoE2Tools/files/6343651/age2_x1.0.zip)

Extract "age2_x1.0.exe" to GamePath\Age2_x1\ then try again.
