### ISSUE TITLE
Directrow Display error for fix error

### ISSUE THREAD

**Issue by himansuahm** [gregstein/AoE2Tools#35]
Hello,
I download AoE2Tools and install in my window 10 operating system because of "Could not initialize graphics system" error in Age of Empires 2.
When i try to fix error than i got error as below and application can't process to download
https://ibb.co/ZfTVFGm

Please provide any solution for me

**Comment by gregstein** [comment]
Hello Himansuahm,

Thank you so much for reporting this. I have pushed a new update to AoE2Tools. Just restart the program and confirm the new update 3.3.2.0.
I appreciate taking the time to reporting this always gestures like this help other users with the same issue. Let me know how it goes.
