### ISSUE TITLE
Bitdefender Gen:Variant.Lazy.96615 

### ISSUE THREAD

**Issue by marklig** [gregstein/AoE2Tools#36]
Bitdefender trojan detects Trojan Gen:Variant.Lazy.96615 
![image](https://user-images.githubusercontent.com/101865547/159000739-2b697d59-adf2-4f63-8889-ee2e35c8690e.png)

Version 3.3.3.0

Access denied while installing regardless of to which folder. Windows 10, but not super excited to run as administrator consider the AV image above.
![image](https://user-images.githubusercontent.com/101865547/159000236-6db04e3f-250f-4b2d-b573-dfac37de103d.png)

**Comment by gregstein** [comment]
Hello,
It's a false positive. AoE2Tools.exe & WK Cloud Installer.exe are both packed using SmartAssembly to optimize performance. Check out virustotal reports:
https://www.virustotal.com/gui/file/acd5806a45cd7b9494ee0e1d4b4ab1c190dfbc602215c79115ba96d1961e67ac
https://www.virustotal.com/gui/file/ddd7a58fd5a89795850cdc4f44e3d992087da04c75438a7171ad62bb2580bca5

Notice how other antivirus giants like Kaspersky and NOD32 report them as clean. Here I will provide you with binaries without any form of packing:

[AoE2Tools-binaries-nopacking.zip](https://github.com/gregstein/AoE2Tools/files/8304888/AoE2Tools-binaries-nopacking.zip)


And these are the reports (your antivirus should no longer ban them out):
https://www.virustotal.com/gui/file/def6f7293fe9529ff68022c38f42fbe7193890f0886dc3dd2792b82b9f1b7846?nocache=1
https://www.virustotal.com/gui/file/775545b59d70e1777a08dfd7403fdd2b5dffe42dc45f2533ca5b2860d584384e?nocache=1

I guess from now on and I will cease packing my binaries to avoid these false positives.

**Comment by marklig** [comment]
Thanks for the reassurance.

**Comment by gregstein** [comment]
I appreciate you for taking the time and reporting this <3

**Comment by MabelVanA** [comment]
In the same vein: Bitdefender flagged Anytxt Searcher as being infected with Gen:Variant.Lazy.152559.  Microsoft's Malware program severely warned as well. Can I safely presume these are false positives as well?
Thanks,
Mabel

**Comment by gregstein** [comment]
Hello MabelVanA,
It's a false positive 100%. Bitdefender and Mcafee are known for inaccurate detections. When your license expires I recommend you Comodo Internet security or Kaspersky Antivirus they are both free solutions and game friendly.

**Comment by MabelVanA** [comment]
Thanks very much! (and sorry I wrote to the wrong repository).

Hans 

 

Van: gregstein ***@***.***> 
Verzonden: donderdag 15 december 2022 11:25
Aan: gregstein/AoE2Tools ***@***.***>
CC: MabelVanA ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [gregstein/AoE2Tools] Bitdefender Gen:Variant.Lazy.96615 (Issue #36)

 

Hello MabelVanA,
It's a false positive 100%. Bitdefender and Mcafee are known for inaccurate detections. When your license expires I recommend you Comodo Internet security it's a free solution and game friendly.
