### ISSUE TITLE
[Feature Request] Bulk Rec Renaming

### ISSUE THREAD

**Issue by Firearrow5235** [gregstein/AoE2Tools#4]
It'd be awesome if you could give AoE2Tools a directory and it would recursively rename every rec in that folder using the same scheme as when you drop an individual rec.

**Comment by gregstein** [comment]
Your request is accepted! Sounds good to me.

**Comment by gregstein** [comment]
Your feature request is available at the latest version of AoE2Tools 3.1.0.5 https://github.com/gregstein/AoE2Tools/releases/tag/3.1.0.5

**Comment by Firearrow5235** [comment]
Thanks for implementing! Just a heads-up, the "renamer" doesn't seem to be functioning. When given a directory it is detecting the recordings (renamed 0/0 changes to renamed 0/26 for example) but clicking "Bulk Rename Now" doesn't rename. It freezes momentarily so it's trying something. I've tried running it in administrator and I've also tried giving it a directory with less than 10 recs. Same result. Let me know if you need any more info or log files.

**Comment by gregstein** [comment]
I just tested and that worked for me. It has renamed all recorded games. Please note that your recorded games must be 1.5 or wololokingdoms version. I will add 1.4rc and lower very soon.
