### ISSUE TITLE
Cannot find my game

### ISSUE THREAD

**Issue by theandychung** [gregstein/AoE2Tools#6]
The tool can't find my game, but I know where the game is. Is there any way I can just tell the tool where my game is?

**Comment by gregstein** [comment]
Hello,

Are you already using the game with voobly? and did you convert using AoE2Tools or Compatibility Patch?

Compatibility Patch is not supported in this version , but the next version that is scheduled soon Today or Tomorrow will support Compatibility Patch and following your request I added an option to manually add custom game folder.

If you are not using compatibility patch, try to open AoE2Tools and Click Settings button Then Options Tab and then click Reset AoE2Tools. This prompts the tool to restart and then you can start a new scan.

If you have Age of Empires 2 HD on Steam you can try this guide https://steamcommunity.com/sharedfiles/filedetails/?id=1459865719

**Comment by gregstein** [comment]
Your feature request is available at the latest version of AoE2Tools 3.1.0.5 https://github.com/gregstein/AoE2Tools/releases/tag/3.1.0.5
