### ISSUE TITLE
Military hotkeys and commands not working anymore since I installed AoE2Tools

### ISSUE THREAD

**Issue by robfrancozone** [gregstein/AoE2Tools#7]
![milbug](https://user-images.githubusercontent.com/26522832/46977094-8306ce80-d0cb-11e8-8969-c1bec08f4925.JPG)
can't patrol, change stance, formation etc. even with hotkeys anymore
This happens in all versions regardless whether AoC 1.0c or WK 5.8.1. How to be able to play properly with controlling units again?

**Comment by robfrancozone** [comment]
jwpToday at 11:00 PM
That is because something reverted your option to have those enabled. It's one of the buttons next to minimap, on the right
Iirc it's the "Advanced Commands" or something

**Comment by gregstein** [comment]
That's correct! The game by default has advanced commands, time disabled. I'll see what I can do to enable them by default. 
Thanks for your time!
