### ISSUE TITLE
Stuck on converting

### ISSUE THREAD

**Issue by robinski25** [gregstein/AoE2Tools#8]
When following "How To Setup AoE2Tools (Article Guide)" with "AoE2Tools.3.1.0.7.exe" on Windows 10 with a fresh instal off AoEHD from Steam i get stuck on the following massage :(

![naamloos](https://user-images.githubusercontent.com/44243427/47111437-d86de780-d253-11e8-8b00-c486d4f82d7c.png)

**Comment by gregstein** [comment]
Hello,

Thank you so much for reporting this! It looks like the dutch language do not have taunts but it's ok! What we can do now as a workaround (until I fix it soon) is to apply a quick fix to trick the converter that the default language is English not Dutch. So please download this zip file I attached here: [langfix.zip](https://github.com/gregstein/AoE2Tools/files/2489266/langfix.zip) , It contains a **langfix.reg** that you need to run. Once you double click it, just confirm yes. Now start converting from the beginning and you should see detecting **Lang: EN** as in this picture: 
![preconverting aoe2tools](https://user-images.githubusercontent.com/16618729/47116468-aa8ba180-d259-11e8-964e-bcb410b49fff.jpg)
 Click "I'm ready" then "Start!" Then it should successfully convert this time.

Let me know how that worked out for you.

**Comment by robinski25** [comment]
Hello,

Thanks for responding so quickly, the fix you sent worked! Even payed services do not respond this fast with a fix, amazing work, thanks!

**Comment by gregstein** [comment]
No problem! And thank you for reporting back and enclosing imagery in your issue It helps a lot.

Do not hesitate to comeback if ever anything comes up.
Have a good day,

**Comment by Gamblore512** [comment]
Hey mate, any chance you could me with this, it seems similar to the above, issue, it's what comes up when I attempt to convert

![Aoe2ToolsErrorMessage](https://user-images.githubusercontent.com/62412246/77132453-ae0d0300-6ab3-11ea-86c4-ada682ab84ed.jpg)

**Comment by gregstein** [comment]
> Hey mate, any chance you could me with this, it seems similar to the above, issue, it's what comes up when I attempt to convert
> 
> ![Aoe2ToolsErrorMessage](https://user-images.githubusercontent.com/62412246/77132453-ae0d0300-6ab3-11ea-86c4-ada682ab84ed.jpg)

Hello friend,

For some reason "drsbuild.exe" is not copied over your steam path. I have enclosed the exe file as a zip file just extract it to this path: 
`C:\Program Files (x86)\Steam\steamapps\common\Age2HD\resources\_common\drs`

[drsbuild.zip](https://github.com/gregstein/AoE2Tools/files/4358979/drsbuild.zip)

it should look like
![drsbuild](https://user-images.githubusercontent.com/16618729/77155434-ca9e4080-6a9d-11ea-833b-719a73d81ee5.png)

Now relaunch AoE2Tools and try to convert again

**Comment by Gamblore512** [comment]
I also have no "drs" folder in the _common folder, will that be an issue?

**Comment by gregstein** [comment]
It is an issue. Your AoE2 HD is missing files. Try to reinstall

**Comment by Gamblore512** [comment]
I have already done a full reinstall once, I also verified the files multiple times, however I will try another reinstall

**Comment by Gamblore512** [comment]
This is fucking painful, I reinstalled, tried to convert, got the same error, managed to get it workling oin voobly, played a game but even though i asked to have my hotkeys trasferred they werent, then i had no DLC civs, so i  installed wolololkingdoms, however i still cant access the dlc civs

**Comment by Gamblore512** [comment]
Ok, I've done a complete uninstall and reinstall and it is now operating correctly, thank you for your help

**Comment by gregstein** [comment]
Thank you for the update! Glad you worked out the problem <3
